version: '3.8'

services:
  fakerestapi-nginx-service:
    container_name: fakerestapi-nginx-container
    image: nginx:1.24.0
    ports: [ "1337:80" ]
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  fakerestapi-php-service:
    container_name: fakerestapi-php-container
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project